### ISSUE TITLE
Update vitest to 1.x

### ISSUE THREAD

**Issue by techniq** [techniq/svelte-ux#216]
We are currently on `vitest` `0.33` as we ran into `Failed to resolve entry for package "@sveltejs/package"` when updating to `0.34` initially.  This sounds like it can be solved by adding `@sveltejs/vite-plugin-svelte` as a direct dependency.

I recently tried to update to the latest `1.2.0` as part of updating to Vite 5 / SvelteKit 2, and ran into `fsevent` errors.  See CI [logs](https://github.com/techniq/svelte-ux/actions/runs/7495881658/job/20406823925?pr=187) on the automated [PR](https://github.com/techniq/svelte-ux/pull/187#issuecomment-1884080929) to update to `0.34`

**Comment by techniq** [comment]
@dimfeld FYI: Added a new issue to track.  I'll take another stab once I ship design tokens / Intl updates, but if you have any ideas, I'm all ears :)

**Comment by dimfeld** [comment]
A few observations:

- Same results with node 20 or 21
- This isn't related to anything that the test itself is doing. If I run just a single test, the test runs and passes but it hits the esbuild error afterward anyway.
![CleanShot 2024-01-15 at 13 11 49](https://github.com/techniq/svelte-ux/assets/1369558/91f72d60-acc3-4b08-bd47-88dcc5147fee)
- Note that the above works best with one of the shorter tests, since whatever is causing the error seems to be runnign concurrently
- Removing the code coverage functionality makes no difference
