### ISSUE TITLE
Tailwind plugin elevation classes do not respect priority

### ISSUE THREAD

**Issue by vanderburg** [techniq/svelte-ux#233]
Attempting to override the shadow on an elevated component by applying .elevation-0 or .shadow-none to the component, both in the classes prop and in settings, but elevation-# from the plugin overrides anything I enter. It also appears that .elevation-2 overrides .elevation-1, and so on. This also happens on Components with no shadow (if I add multiple elevation classes, the higher number takes priority) and on regular HTML elements.

![shdow](https://github.com/techniq/svelte-ux/assets/4179091/74b52360-d135-4292-b028-ce6ecd3fb262)

In the above image, that is produced, regardless of the order of the classes.

**Comment by vanderburg** [comment]
Apparently, you can add a class as "!elevation-0", which is the same as applying "!important" to all of its properties. It's not elegant, since I feel like any time I have to use !important, I'm doing something wrong, but it's workable.

**Comment by techniq** [comment]
I believe the issue is we just need to add `elevation-1` ... `elevation-24` to the tailwind-merge [config](https://github.com/techniq/svelte-ux/blob/next/packages/svelte-ux/src/lib/utils/styles.ts#L28) so it knows to not overlap.  Second, I think we could add `elevation-none` to set `box-shadow: none`.
