### ISSUE TITLE
Drawer + Dialog shading on browser reload

### ISSUE THREAD

**Issue by neilmfrench** [techniq/svelte-ux#403]
First of all, thanks for the library - definitely the best Svelte UI library out right now!

I am doing something similar to [this](https://svelte-ux.techniq.dev/docs/components/Drawer#dialog-within-drawer), where I have a Drawer open first, then a Dialog inside of it. I am doing this declaratively, e.g. user navigates to /place/1 -> Drawer is open, user navigates to /place/1/dialog -> Drawer and dialog are both open.

When this is done from actions performed on the UI, like clicking the button that navigates to /place/1 and then clicking another button to navigate to /place/1/dialog, this all works perfectly.

My issue is when I go directly to /place/1/dialog, for example by opening it directly in a new browser tab, the shading on the Drawer is not present. Hopefully the following pictures illustrate that: 

Correct - through interactions on the UI
![drawer-correct](https://github.com/techniq/svelte-ux/assets/9321923/8338867f-fa0f-407d-959b-4612c5cce768)

No shading - through going directly to the URL
![drawer-incorrect](https://github.com/techniq/svelte-ux/assets/9321923/c5af2877-eadb-48fb-83ad-674786bbf497)

I could probably hack around this in CSS, but I wanted to see if this is a potential bug first.

**Comment by techniq** [comment]
Hey @neilmfrench, thanks for the kind words. I have not tried route based Dialog/Drawer like you are using, but definitely feels like a bug with the Backdrop ordering or rendering of Dialog/Drawer (they are portal’s to the bottom). Could also be SSR related. Could you create a small repo on Stackblitz or similar I could investigate the issue?

**Comment by neilmfrench** [comment]
Thanks @techniq, hopefully this is enough to see it in action: https://stackblitz.com/edit/github-kaggbw-ei6tie?file=src%2Froutes%2Fpage%2F%2Blayout.svelte 

If you click through the UI using the navbar by going to Page -> Close button, you should see it working fine. If you go directly to the url .../page/subpage or even refresh with the Dialog open, you'll notice the shading of the drawer is off.

**Comment by techniq** [comment]
Thanks @neilmfrench, that was exactly what I needed (I ended up pulling it locally as it was a little easier to see the URL and test).

So the issue is the order of `Backdrop` being rendered differently on refresh (should be immediately before the related `Drawer`/`Dialog`) and caused by portal'ing these to the bottom of the DOM (body element) to  guarantee there isn't inadvertent styles inherited.

Initial | Refresh
--- | ---
![image](https://github.com/techniq/svelte-ux/assets/177476/dda9ec9a-9ebd-487b-94a1-ae0b828f3442) | ![image](https://github.com/techniq/svelte-ux/assets/177476/0f4b7120-37c8-4003-a0ca-07c8130df933)
![image](https://github.com/techniq/svelte-ux/assets/177476/fba98cc5-99f6-4f36-a78d-f93cb8a84482) | ![image](https://github.com/techniq/svelte-ux/assets/177476/77b5dc19-cf0e-4d25-923a-6ee90a672239)

There are 2 solutions / workarounds.  Simply moving the `<slot>` below the `<Drawer>` instead of within it will fix the issue.

```svelte
<Drawer
  bind:open={rightOpen}
  placement="right"
  class="w-[550px]"
  on:outroend={close}
>
  <h2>Some content</h2>
  <div slot="actions">
    <Button on:click={create}>Close</Button>
  </div>
</Drawer>

<!-- move this -->
<slot />
```

or you can pass `portal={false}` to either `<Drawer>` or `<Dialog>` so one is not portal'd to the bottom.  Note, if you do this to the `<Dialog>` the relative context for the absolutely positioned `Dialog` will be the `Drawer`, and thus change the display.

![image](https://github.com/techniq/svelte-ux/assets/177476/4bd3a042-a6ca-4160-8e86-b0f48bad8656)
