### ISSUE TITLE
Number Stepper should use touch-action: manipulation

### ISSUE THREAD

**Issue by dippa-1** [techniq/svelte-ux#412]
Hi,
first of all, cool project.
When scrolling through the components, I've noticed that the number stepper would zoom in on mobile devices after tapping twice. I had this issue myself a few weeks ago.

Sorry that I don't have the time right now to dig into the code and create a PR, but the NumberStepper buttons should use the css property:
`touch-action: manipulation;`
More info: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

Maybe this is also relevant for other buttons, I am not sure.

Thanks :)

**Comment by techniq** [comment]
@dippa-1 Good callout!  I added it to all `<Button>` instances by default as I think it made the most sense.

A lot of the times I'll add `touch-action: pan-x pan-y` to the `body` of my sites since they are more app-like, but it's a bit heavy handed (there are always cases where it can be nice to pinch-zoom, such as looking closer at an image).
